update packages
TappNetwork/laravel-aws-secrets-manager pull request #23
Opened 2022-04-15 15:12 UTC by Null78

updated the packages and fixed some comments
to support latest version of Laravel 9.8

2022-04-26 10:17 UTC, swilla requested changes
Thank you! I'd rather not break previous version support. Can you update the dependencies?

2022-04-26 10:17 UTC, swilla commented on composer.json
> +        "illuminate/support": "^9.8"
Can you add back the previous version support? 

```suggestion
        "php": "^7.4 || ^8.0",
        "aws/aws-sdk-php": "^3.219",
        "illuminate/support": "^6.0 || ^7.0 || ^8.0 || ^9.8"
```

2022-04-26 10:17 UTC, swilla commented
Also, need to update the workflow matrix to run tests on L9 too: 
https://github.com/TappNetwork/laravel-aws-secrets-manager/blob/master/.github/workflows/run-tests-l8.yml

2022-05-01 12:02 UTC, Null78 commented
> Also, need to update the workflow matrix to run tests on L9 too: https://github.com/TappNetwork/laravel-aws-secrets-manager/blob/master/.github/workflows/run-tests-l8.yml

can you please check it ?

2022-05-02 15:15 UTC, swilla requested changes

2022-05-02 15:15 UTC, swilla commented on composer.json
> +        "orchestra/testbench": "^7.4",
I think you need multiple versions here. I approved the actions to run and you can see which ones are failing now.

2022-05-02 16:27 UTC, swilla requested changes

2022-05-02 16:27 UTC, swilla commented on .github/workflows/run-tests-l9.yml
Can you add exclude: 
```
exclude:
    - laravel: 9.*
      php: 7.* 
```

2022-05-02 16:47 UTC, swilla approved these changes

2022-05-02 16:47 UTC, merged

2022-05-02 16:54 UTC, Null78 commented
ok I actually removed some commits because I was testing
but you merged anyway

thanks

2022-05-02 17:46 UTC, swilla commented
All the tests were passing for me. Let me know if I missed something.